Part2
polis-mail-ru/2021-ads pull request #37
Opened 2021-09-30 20:48 UTC by LutsenkoDm

1-5. 
Луценко Дмитрий

2021-09-30 21:19 UTC, lamtev requested changes
1. Оптимизировать merge
2. Ответить на вопрос

2021-09-30 21:19 UTC, lamtev commented on src/main/java/HomeWork2Task1.java
> +        private int score;
final

2021-09-30 21:19 UTC, lamtev commented on src/main/java/HomeWork2Task1.java
> +        Participant[] rightArray = new Participant[r];
Стоит оптимизировать по памяти. Есть способ не аллоцировать 2 массива на каждый merge

2021-09-30 21:19 UTC, lamtev commented on src/main/java/HomeWork2Task4.java
> +        out.println(set.size()); */
Это было бы эффективнее по времени или по памяти, чем решение с помощью сортировки?

2021-09-30 21:19 UTC, lamtev commented on src/main/java/HomeWork2Task1.java
> -            merge(participants, fromInclusive, mid, toInclusive);
👍🏻

2021-10-01 09:28 UTC, LutsenkoDm commented on src/main/java/HomeWork2Task1.java
> +        private int score;
Добавил

2021-10-01 09:29 UTC, LutsenkoDm commented on src/main/java/HomeWork2Task1.java
> +        Participant[] rightArray = new Participant[r];
rightArray убрал везде, где использовал merge

2021-10-01 09:39 UTC, LutsenkoDm commented on src/main/java/HomeWork2Task4.java
> +        out.println(set.size()); */
По времени должно быть эффективнее, так как в среднем добавление за O(1), то есть получим O(n) добавляя все элементы. Сортировка это уже O(nlog(n)) + при сортировке надо сначала прочитать, а потом обрабатывать массив, а так все за 1 действие происходит. По памяти скорее нет хотя бы из-за использования объектов.

2021-10-01 09:39 UTC, LutsenkoDm commented on src/main/java/HomeWork2Task1.java
> -            merge(participants, fromInclusive, mid, toInclusive);
Сам не знаю откуда 2-я взялась, на тестах её не было)

2021-10-01 09:53 UTC, lamtev commented on src/main/java/HomeWork2Task4.java
> +        out.println(set.size()); */
Всё так

2021-10-01 09:55 UTC, lamtev requested changes

2021-10-01 09:55 UTC, lamtev commented on src/main/java/HomeWork2Task1.java
> +        Participant[] leftArray = new Participant[l];
Можно еще лучше (вообще в merge не придется создавать новые массивы)

2021-10-01 11:03 UTC, LutsenkoDm commented on src/main/java/HomeWork2Task1.java
> +        Participant[] leftArray = new Participant[l];
Я так понимаю имеется в виду модифицированный вариант merge sort, который по памяти O(1). Я реализовывал обычный вариант, в нем вроде O(n) по памяти (как у меня) и лучше уже нельзя для него. Как по мне модифицированный вариант для данных задач это немного лишнее и если стоит вопрос памяти, то проще уже переписать на quick sort так как устойчивость не важна.

2021-10-01 11:25 UTC, lamtev commented on src/main/java/HomeWork2Task1.java
> +        Participant[] leftArray = new Participant[l];
Не, я же не садист. Речь просто про то, что можно использовать 1 массив размера исходного сортируемого массива для всех операций слияния. Не придется на каждом слиянии заводить новый массив

2021-10-01 11:56 UTC, LutsenkoDm commented on src/main/java/HomeWork2Task1.java
> +        Participant[] leftArray = new Participant[l];
Исправил. Сначала подумал, что вообще без временных массивов надо сделать.

2021-10-01 18:44 UTC, lamtev approved these changes

2021-10-01 18:45 UTC, lamtev commented
Принято

2021-10-01 18:45 UTC, closed without merging