Homework Week 2
polis-mail-ru/2021-ads pull request #41
Opened 2021-10-01 21:42 UTC by radkoff26

Радько Вячеслав

2021-10-01 21:56 UTC, lamtev requested changes
1. Исправить замечания
2. Хотя бы в одной из задач, которые были решены с помощью красно-черных деревьев/хэш-таблиц, сравнить сложность по времени и памяти с новой реализацией, которая будет выполнена с помощью какой-либо сортировки

2021-10-01 21:56 UTC, lamtev commented on src/main/java/Week2Task2.java
> +            }
Нужно решить эту задачу с использованием знаний, полученных на последнем занятии, то есть с помощью сортировок

Более того, текущее решение использует готовые реализации алгоритмов JDK, что тоже не допускается:

> Во всех задачах запрещается использовать готовые реализации алгоритмов из JDK

2021-10-01 21:56 UTC, lamtev commented on src/main/java/Week2Task4.java
> +        HashSet<String> set = new HashSet<>();
Нужно решить эту задачу с использованием знаний, полученных на последнем занятии, то есть с помощью сортировок

Более того, текущее решение использует готовые реализации алгоритмов JDK, что тоже не допускается:

> Во всех задачах запрещается использовать готовые реализации алгоритмов из JDK

2021-10-01 21:56 UTC, lamtev commented on src/main/java/Week2Task5.java
> +        HashSet<String> set2 = new HashSet<>();
Нужно решить эту задачу с использованием знаний, полученных на последнем занятии, то есть с помощью сортировок

Более того, текущее решение использует готовые реализации алгоритмов JDK, что тоже не допускается:

> Во всех задачах запрещается использовать готовые реализации алгоритмов из JDK

2021-10-02 21:20 UTC, radkoff26 commented
Если выполнять данные задачи с помощью различных структур данных, то можно понять, что сложность по времени и памяти отличается.
Например:
В задаче B можно было использовать TreeMap (сортировка подсчётом), а можно было воспользоваться одним из алгоритмов сортировки, основанном на сравнениях. В первом случае получаем стабильные nlogn, но при этом сложность по памяти будет больше, так как хранится множество ссылок на объекты TreeMap. А во втором сложность по времени может варьироваться в зависимости от данных, хотя сложность по памяти будет отличаться от первого способа в лучшую сторону, так как мы храним просто массив чисел (ну и в самом алгоритме (в моём случае merge sort) храним некоторое количество массивов).
А в задачах D и E можно было воспользоваться HashSet и обойтись без сортировок вообще, что улучшило бы сложность по скорости в несколько раз (O(n) - не более чем переборы входных элементов и передача их в HashSet).

2021-10-02 21:56 UTC, lamtev commented
> Если выполнять данные задачи с помощью различных структур данных, то можно понять, что сложность по времени и памяти отличается. Например: В задаче B можно было использовать TreeMap (сортировка подсчётом), а можно было воспользоваться одним из алгоритмов сортировки, основанном на сравнениях. В первом случае получаем стабильные nlogn

1) TreeMap - это то же самое, что и сортировка подсчётом?
2) Сортировка подсчётом работает за nlogn ?

2021-10-02 22:02 UTC, lamtev requested changes

2021-10-02 22:02 UTC, lamtev commented on src/main/java/Week2Task4.java
> +        long[] aRight = new long[r - mid];
На каждый merge создается по 2 массива общей длины r - l + 1. Это неэффективно: можно попробовать посчитать сколько будет аллоцировано суммарно памяти за всю сортировку. Стоит оптимизировать, выполняя все слияния в одном массиве длины исходного сортируемого массива.

2021-10-03 08:45 UTC, radkoff26 commented
> > Если выполнять данные задачи с помощью различных структур данных, то можно понять, что сложность по времени и памяти отличается. Например: В задаче B можно было использовать TreeMap (сортировка подсчётом), а можно было воспользоваться одним из алгоритмов сортировки, основанном на сравнениях. В первом случае получаем стабильные nlogn
> 
> 1. TreeMap - это то же самое, что и сортировка подсчётом?
> 2. Сортировка подсчётом работает за nlogn ?

2021-10-03 08:45 UTC, closed without merging

2021-10-03 12:51 UTC, lamtev commented
> Нет, TreeMap - это не то же самое. Просто сортировку подсчётом делать с такими большими числами делать сложно (хотя мне кажется, что в задании B можно сделать её с учётом условия про разницу на 107)

А в чем сложность? Как ты уже сказал, можно положиться на разницу в 107 из условия задачи. А можно решить в более общем виде: за линейный проход найти min и max. Дополнительной памяти потребуется k = max - min + 1

2021-10-03 12:53 UTC, radkoff26 commented
Согласен, так проще