Ponomarev Stepan HW 2
polis-mail-ru/2021-ads pull request #45
Opened 2021-10-03 12:01 UTC by step-ponomarev

2021-10-03 12:01 UTC, step-ponomarev commented on src/main/java/ru/mail/polis/ads/ponomarev/stepan/part2/Task5.java
> +package ru.mail.polis.ads.ponomarev.stepan.part2;
Не проходит тесты

2021-10-03 15:00 UTC, lamtev requested changes
1. Исправить замечания
2. Ответить на вопросы
3. Еще есть время решить последнюю задачу, чтобы получить за такое простое ДЗ максимум баллов

2021-10-04 19:37 UTC, step-ponomarev commented on src/main/java/ru/mail/polis/ads/ponomarev/stepan/part2/Task2.java
> +    final static int MAX_SIZE = DIFFERENCE * 2;
Ну мы потому что заранее не знаем "в какую сторону у нас будет отклонение", поэтому готовимся к худшему так сказать)

2021-10-04 19:44 UTC, step-ponomarev commented on src/main/java/ru/mail/polis/ads/ponomarev/stepan/part2/Task1.java
> +    public static void sort(OlympChel[] array, int lb, int rb) {
Все формальности соблюдены!  😎.🤝 😎

2021-10-04 19:44 UTC, step-ponomarev commented on src/main/java/ru/mail/polis/ads/ponomarev/stepan/part2/Task4.java
> +    private static class Derevo {
Спасибо!

2021-10-05 04:50 UTC, lamtev approved these changes

2021-10-05 04:51 UTC, lamtev commented
Принято за 10 баллов
Есть время добить последнюю задачу

2021-10-09 21:43 UTC, lamtev commented
Будет решение последней задачи?

2021-10-10 18:40 UTC, lamtev commented
принято полностью

2021-10-10 18:40 UTC, closed without merging