Homework Week 2
polis-mail-ru/2021-ads pull request #46
Opened 2021-10-03 13:45 UTC by radkoff26

Радько Вячеслав
Переделал задание B - сделал сортировку подсчётом

2021-10-03 14:09 UTC, lamtev requested changes
1. Merge sort так и остался без изменений
2. В будущем лучше все исправления делать в рамках одного Pull Request, чтобы было видно историю исправлений и комментарии, и проверяющим было проще ориентироваться.

2021-10-03 14:12 UTC, radkoff26 commented
> 1. Merge sort так и остался без изменений
> 2. В будущем лучше все исправления делать в рамках одного Pull Request, чтобы было видно историю исправлений и комментарии, и проверяющим было проще ориентироваться.

Понял. Я просто ещё не успел его сделать

2021-10-03 14:16 UTC, lamtev commented
> > 1. Merge sort так и остался без изменений
> > 2. В будущем лучше все исправления делать в рамках одного Pull Request, чтобы было видно историю исправлений и комментарии, и проверяющим было проще ориентироваться.
> 
> Понял. Я просто ещё не успел его сделать

Ок. 3 задачи приняты в полной мере. По двум с merge sort для получения полного балла требуется доработка

2021-10-04 17:13 UTC, radkoff26 commented
> Радько Вячеслав Переделал задание B - сделал сортировку подсчётом

2021-10-04 17:15 UTC, radkoff26 commented
Использовал quick sort, т. к. его сложность по памяти O(logn), когда сложность merge sort с одним массивом - O(n)

2021-10-04 18:10 UTC, lamtev approved these changes

2021-10-04 18:11 UTC, lamtev commented
принято

2021-10-04 18:11 UTC, closed without merging