Part2
polis-mail-ru/2021-ads pull request #48
Opened 2021-10-03 17:02 UTC by AirBurn0

Байдия Р.
1-5 Все работает

2021-10-05 05:15 UTC, lamtev requested changes

2021-10-05 05:15 UTC, lamtev commented on src/main/java/Week2Test1.java
> +            Member[] rarray = new Member[r];
Нужно оптимизировать использование памяти: достаточно 1 раз создать вспомогательный массив длины исходного массива, и использовать его для ВСЕХ слияний. То есть 1 массив на всю сортировку вместо 2 массивов на каждое слияние

2021-10-05 09:42 UTC, AirBurn0 commented on src/main/java/Week2Test1.java
> +            Member[] rarray = new Member[r];
исправил

2021-10-09 21:07 UTC, lamtev approved these changes

2021-10-09 21:07 UTC, lamtev commented
принято

2021-10-09 21:07 UTC, closed without merging