Part2
polis-mail-ru/2021-ads pull request #49
Opened 2021-10-03 22:33 UTC by coradead

2021-10-05 05:17 UTC, lamtev requested changes
Без фамилии непонятно кто вы

2021-10-05 09:00 UTC, coradead commented
Галеев Артур Рамилевич

2021-10-09 21:25 UTC, lamtev approved these changes

2021-10-09 21:26 UTC, lamtev commented
принято

2021-10-09 21:26 UTC, closed without merging