HW2
polis-mail-ru/2021-ads pull request #50
Opened 2021-10-04 01:48 UTC by Sanerins

Все задания успешно решены
Александр Косницкий

2021-10-05 05:34 UTC, lamtev requested changes

2021-10-05 05:34 UTC, lamtev commented on src/main/java/homework2/TaskA.java
> +    private static void bubbleSort(int[][] array) {
> В задаче A необходимо написать функцию сортировки, которая либо принимает в качестве аргумента Comparator помимо массива, либо принимает массив элементов, реализующих интерфейс Comparable.

ДЗ2

2021-10-05 05:34 UTC, lamtev commented on src/main/java/homework2/TaskB.java
> +        int[] numbers = new int[216];
Как получилось 216?

2021-10-05 05:34 UTC, lamtev commented on src/main/java/homework2/TaskD.java
> +        int[] r = new int[arr.length - middle];
В текущей реализации merge sort создается по 2 массива на каждое слияние. А можно выполнить все слияния в одном вспомогательном массиве. И тогда получится 1 массив на всю сортировку вместо 2-х на каждое слияние

2021-10-05 07:39 UTC, Sanerins commented on src/main/java/homework2/TaskB.java
> +        int[] numbers = new int[216];
На самом деле хватило бы `215`, на что я и изменю, логика за этим числом такая: если разница между двумя числами не превышает `107`, то любое число после первого в нашем массиве чисел в предельном случае будет либо на `107` больше, либо на 107 меньше, поэтому нужно кол-во элементов равное `[x-107;x+107]` (все включительно). Проще всего взять за x(так как он произвольный) `107`, тогда выходит `[0, 214]`, а это действительно `215` элементов, а не 216: просчитался немного изначально)
Стоит отметить, что все эл-ты в нашем массиве никогда не будут заняты одновременно, так как разница между ними легко может быть больше `107`, однако нам все же нужно иметь возможность поставить наш первый элемент в середину, иначе алгоритм стал бы сложнее, например нам надо было бы пройтись лишний раз по массиву чтобы найти максимум и поставить его на последнее место, но так как памяти на 107 лишних элементов уходит мало, а массив может быть очень большой длинны и проходиться по нему еще раз не хочется, мы и берем именно `215`, как размер нашего массива

2021-10-05 12:12 UTC, Sanerins commented on src/main/java/homework2/TaskA.java
> +    private static void bubbleSort(int[][] array) {
Исправлено, создан класс, реализующий необходимый интерфейс

2021-10-05 12:12 UTC, Sanerins commented on src/main/java/homework2/TaskD.java
> +        int[] r = new int[arr.length - middle];
Исправлено, теперь метод более оптимальный в этом плане

2021-10-09 21:13 UTC, lamtev requested changes

2021-10-09 21:13 UTC, lamtev commented on src/main/java/homework2/TaskD.java
> +        subMergeSort(arr, swap, middle, arr.length);
Для чего subMergeSort? Какое-то дублирование получается

2021-10-11 17:31 UTC, lamtev commented
@Sanerins ответишь на вопрос в ревью?

2021-10-13 18:50 UTC, closed without merging

2021-10-15 09:15 UTC, Sanerins commented on src/main/java/homework2/TaskD.java
> +        subMergeSort(arr, swap, middle, arr.length);
Да, действительно можно было бы сделать вызов так, я тоже об этом думал, однако решил все же реализовать его таким образом, так как слышал, что рекурсию лучше сокращать как можно сильнее, ибо иначе может произойти много неприятных вещей, таких, как переполнение стека. С другой стороны, сокращение рекурсии на один вызов действительно не несёт прямо-таки большого снижения нагрузки, вызываемой ей, поэтому данную оптимизацию можно и опустить, как ненужную, но мне казалось, что мол раз можно немного сократить количество вызовов, сделав первое действие в итеративном методе, за счёт буквально пары дополнительных строк, то почему бы и нет