Homework 2
polis-mail-ru/2021-ads pull request #57
Opened 2021-10-04 18:59 UTC by donebd

Love merge sort

2021-10-05 06:54 UTC, lamtev requested changes
1. В задаче B есть подсказка - какую сортировку использовать (не merge sort). Давай переделаем
2. Раз уж всё решено merge sort, давай она хотя бы будет ± крутой: не нужно создавать новый вспомогательный массив на каждое слияние, ведь достаточно создать 1 массив и все слияния выполнять в нём

2021-10-05 09:40 UTC, donebd commented
Неправильно прочитал условие, думал никакие соседние 2 не различаются на 107.

2021-10-05 09:45 UTC, donebd commented
fixed

2021-10-09 21:21 UTC, lamtev approved these changes

2021-10-09 21:21 UTC, closed without merging